version: "3"
#도커컴포즈는 컨테이너를 서비스라고 함.
services:
  # 서비스명을 기본 호스트네임으로 잡는다. hostname: redis
  redis:
    image: "redis:latest"
    #hostname: 이렇게 지정해도 됨
    ports:
      - "6379:6379" # Redis의 기본 포트입니다.#레빗 같은 경우에 배열로 넣기 때문에 - 하고 추가한다
    networks:
      - my-network
  app:
    image: "hbin1028/commerce" # 여기에 (Spring Boot 도커 이미지 이름) 또는 (dockerhub respository명)을 사용하세요.
    #commerce:latest, commerce:v1 <<같이 특정한 것을 선택 가능
    ports:
      - "8081:8081" # 호스트의 포트를 컨테이너의 포트에 매핑합니다.
    networks:
      - my-network
    volumes:
      # 호스트 경로 : 컨테이너 경로
      # c:/tmp:/tmp
      # 호스트 볼륨명:컨테이너경로
      #--------------------------
      # 우분투 리눅스 볼륨위치
      # /var/lib/docker/volumes
      # 윈도우즈 볼륨위치
      # \\wsl$\docker-desktop-data\data\docker\volumes
      #--------------------------
      - my-volume:/tmp
    # 먼저 실행되어야 할 서비스(컨테이너) 목록
    depends_on:
      - redis
    # 서비스 실행할 때 사용할 환경 변수(컨테이너에서 사용할 변수)
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  #네트워크 정의 영역
  #스프링에서 스레드를 관리하게끔 여기서 설정해줘야 함.
  #노드JS는 싱글스레드이기 때문에 운영체제에서 관리하거나 툴을 써야 함.
networks:
  my-network:
    driver: bridge
volumes:
  my-volume:
